### ISSUE TITLE
Declaration of usage 

### ISSUE THREAD

**Issue by marcus-sa** [RaccoonCH/Rakkit#17]
What's the reason for why people would choose this over `@nestjs/graphql`? The syntax is just an exact copy.

**Comment by ngmariusz** [comment]
I have read this https://dev.to/owen/rakkit-create-your-graphql-and-rest-apis-with-typescript-and-decorators-cnj and i also would like to know why/when rakkit over nestjs

**Comment by marcus-sa** [comment]
There's really no point in reinventing the wheel when Nest consists of such a big community.

**Comment by OwenCalvin** [comment]
Initially, we had planned to integrate type-graphql (used by nest) directly into Rakkit, without redeveloping it, the goal is not to reinvent the wheel but to have our own implementation of the package, because we can provide a more consistent ecosystem, such as using the same middleware for GraphQL and REST. We also fixed some issues, such as the fact that type-graphql does not allow to create multidimensional arrays or add enums based on classes (https://github.com/19majkel94/type-graphql/issues/39). Rakkit's goal was, at the base, to allow the creation of a Headless CMS based on it, this framework (this repo) is a part of this project and both will therefore evolve together to provide flexibility (for example: to install only the Rakkit packages wanted for a project) and features 😊
(We also wanted to use the minimum number of modules.)
And GraphQL is not the only feature of Rakkit...

**Comment by MichalLytek** [comment]
> We also fixed some issues, such as the fact that type-graphql does not allow to create multidimensional arrays or add enums based on classes 

The spirit of OSS is that you create a PR with the changes, not create an own copy with own fixed based on someone work.
